#!/usr/bin/env bash
echo "------pre-commit------"

PROJECTDIR=`git rev-parse --show-toplevel`

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2
# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against


git secrets --pre_commit_hook -- "$@"
echo "----------end---------"
