#!/bin/bash
echo "------pre-commit------"

PROJECTDIR=`git rev-parse --show-toplevel`

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2
# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against

##Custom Config
echo "atom package list update...."

apm upgrade
apm list -i -b > $PROJECTDIR/atom/atom-packages
git add $PROJECTDIR/atom/atom-packages

echo "----------end---------"
